sessions:
  session1:
    title: "Reactjs"
    date: "dd/mm/yy"
  session2:
    title: "Android"
    date: "dd/mm/yy"
  session3:
    title: "Python"
    date: "dd/mm/yy"
  session4:
    title: "Machine Learing"
    date: "dd/mm/yy"
